# Generated by Django 4.1 on 2025-11-10 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vagas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo_vaga", models.CharField(blank=True, max_length=100, null=True)),
                ("descricao_vaga", models.TextField(blank=True, null=True)),
                (
                    "requisito_vaga",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("local", models.CharField(blank=True, max_length=255, null=True)),
                ("data_publicacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="ativa", max_length=255, null=True
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to="empresa.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioVaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_candidatura", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vagas.vagas"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CursoVaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curso", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vagas.vagas"
                    ),
                ),
            ],
        ),
    ]
