# Generated by Django 4.1 on 2025-10-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_alter_empresa_hubs_alter_empresahub_hub'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_vaga', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_vaga', models.TextField(blank=True, null=True)),
                ('requisito_vaga', models.TextField(blank=True, null=True)),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_vaga', models.CharField(blank=True, max_length=255, null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vagas')),
            ],
        ),
    ]
