# Generated by Django 4.1 on 2025-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vagas",
            name="requisito_vaga",
            field=models.TextField(blank=True, null=True),
        ),
    ]
