# Generated by Django 4.1 on 2025-10-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='tipo_vaga',
        ),
        migrations.AddField(
            model_name='vagas',
            name='carga_horaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vagas',
            name='empresa_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='empresa_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='status',
            field=models.CharField(blank=True, default='ativa', max_length=255, null=True),
        ),
    ]
