# Generated by Django 4.1 on 2025-10-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_remove_vagas_tipo_vaga_vagas_carga_horaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='carga_horaria',
        ),
    ]
