# Generated by Django 4.1 on 2025-10-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_remove_vagas_carga_horaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='curso',
        ),
        migrations.CreateModel(
            name='CursoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vagas')),
            ],
        ),
    ]
