# Generated by Django 4.1 on 2025-10-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_hubs_alter_empresahub_hub'),
        ('vagas', '0004_remove_vagas_curso_cursovaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='empresa.empresa'),
        ),
    ]
