# Generated by Django 4.1 on 2025-10-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_hubs_alter_empresahub_hub'),
        ('vagas', '0005_alter_vagas_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='empresa_cidade',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='empresa_estado',
        ),
        migrations.AddField(
            model_name='vagas',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='requisito_vaga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
