# Generated by Django 4.1 on 2026-04-22 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_remove_usuariotreinamentos_treinamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('data_evento_inicio', models.DateField(blank=True, null=True)),
                ('data_evento_fim', models.DateField(blank=True, null=True)),
                ('horario_evento', models.TimeField(blank=True, null=True)),
                ('local_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('publico_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_evento', models.TextField(blank=True, max_length=500, null=True)),
                ('vagas_disponiveis', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.hub')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_evento_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('presenca', models.CharField(choices=[('pendente', 'Pendente'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='pendente', max_length=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição em Evento',
                'verbose_name_plural': 'Inscrições em Eventos',
                'ordering': ['data_inscricao'],
                'unique_together': {('evento', 'usuario')},
            },
        ),
    ]
