# Generated by Django 4.1 on 2026-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='isActivate',
            field=models.BooleanField(default=True),
        ),
    ]
