# Generated by Django 4.1 on 2025-11-10 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsuarioBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("nome", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("tipo", models.CharField(max_length=10)),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="fotos_perfil/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "jpeg"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_estado", models.CharField(max_length=100)),
                ("sigla_estado", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Hub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_hub", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=250)),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="fotos_hub/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "jpeg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cidade", models.CharField(max_length=100)),
                (
                    "estado_cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.estado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_nascimento", models.DateField()),
                ("genero", models.CharField(max_length=255)),
                ("estado_civil", models.CharField(max_length=255)),
                ("nacionalidade", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=20)),
                ("cep", models.CharField(max_length=10)),
                ("rua", models.CharField(max_length=255)),
                ("bairro", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cargo_pretendido",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "area_interesse",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pretensao_salarial",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "disponibilidade",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instituicao_nome1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grau_escolaridade1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "curso_graduacao1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "situacao_academica1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_acad_inicio1", models.DateField(blank=True, null=True)),
                ("data_acad_fim1", models.DateField(blank=True, null=True)),
                (
                    "instituicao_nome2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grau_escolaridade2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "curso_graduacao2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "situacao_academica2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_acad_inicio2", models.DateField(blank=True, null=True)),
                ("data_acad_fim2", models.DateField(blank=True, null=True)),
                (
                    "instituicao_nome3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grau_escolaridade3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "curso_graduacao3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "situacao_academica3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_acad_inicio3", models.DateField(blank=True, null=True)),
                ("data_acad_fim3", models.DateField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("instagram", models.CharField(blank=True, max_length=100, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("site_pessoal", models.URLField(blank=True, null=True)),
                ("competencias_tecnicas1", models.TextField(blank=True, null=True)),
                (
                    "competencias_comportamentais1",
                    models.TextField(blank=True, null=True),
                ),
                ("competencias_tecnicas2", models.TextField(blank=True, null=True)),
                (
                    "competencias_comportamentais2",
                    models.TextField(blank=True, null=True),
                ),
                ("competencias_tecnicas3", models.TextField(blank=True, null=True)),
                (
                    "competencias_comportamentais3",
                    models.TextField(blank=True, null=True),
                ),
                ("pessoa_com_deficiencia", models.BooleanField(default=False)),
                (
                    "tipo_deficiencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("necessidade_adaptacao", models.TextField(blank=True, null=True)),
                ("remoto", models.BooleanField(default=False)),
                ("interesses_hobbies", models.TextField(blank=True, null=True)),
                (
                    "curriculo_pdf",
                    models.FileField(blank=True, null=True, upload_to="curriculos/"),
                ),
                (
                    "carta_apresentacao",
                    models.FileField(blank=True, null=True, upload_to="cartas/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.cidade"
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.estado"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.CreateModel(
            name="Idioma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idioma1", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nivel_fluencia1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("idioma2", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nivel_fluencia2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("idioma3", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nivel_fluencia3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idiomas",
                        to="core.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperienciaProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_empresa1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cargo1", models.CharField(blank=True, max_length=255, null=True)),
                ("data_inicio1", models.DateField(blank=True, null=True)),
                ("data_fim1", models.DateField(blank=True, null=True)),
                (
                    "nome_empresa2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cargo2", models.CharField(blank=True, max_length=255, null=True)),
                ("data_inicio2", models.DateField(blank=True, null=True)),
                ("data_fim2", models.DateField(blank=True, null=True)),
                (
                    "nome_empresa3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cargo3", models.CharField(blank=True, max_length=255, null=True)),
                ("data_inicio3", models.DateField(blank=True, null=True)),
                ("data_fim3", models.DateField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiencias",
                        to="core.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CursoExtraCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_curso1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instituicao1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("carga_horaria1", models.PositiveIntegerField(blank=True, null=True)),
                ("data_conclusao1", models.DateField(blank=True, null=True)),
                ("link_certificado1", models.URLField(blank=True, null=True)),
                (
                    "nome_curso2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instituicao2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("carga_horaria2", models.PositiveIntegerField(blank=True, null=True)),
                ("data_conclusao2", models.DateField(blank=True, null=True)),
                ("link_certificado2", models.URLField(blank=True, null=True)),
                (
                    "nome_curso3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instituicao3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("carga_horaria3", models.PositiveIntegerField(blank=True, null=True)),
                ("data_conclusao3", models.DateField(blank=True, null=True)),
                ("link_certificado3", models.URLField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos_extras",
                        to="core.usuario",
                    ),
                ),
            ],
        ),
    ]
