# Generated by Django 4.1 on 2025-09-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='estado_civil',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='genero',
        ),
    ]
