# Generated by Django 4.1 on 2025-12-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eventos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_evento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_evento_inicio", models.DateField(blank=True, null=True)),
                ("data_evento_fim", models.DateField(blank=True, null=True)),
                ("horario_evento", models.TimeField(blank=True, null=True)),
                (
                    "local_evento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "publico_evento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "descricao_evento",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treinamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_treinamentos",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_treinamento_inicio", models.DateField(blank=True, null=True)),
                ("data_treinamento_fim", models.DateField(blank=True, null=True)),
                ("horario_treinamento", models.TimeField(blank=True, null=True)),
                (
                    "local_treinamento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "publico_treinamento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "descricao_treinamento",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioTreinamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treinamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.treinamentos",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioEventos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.eventos"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
                    ),
                ),
            ],
        ),
    ]
