# Generated by Django 4.1 on 2025-11-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="curso_graduacao",
            new_name="curso_graduacao1",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="grau_escolaridade",
            new_name="curso_graduacao2",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="instituicao_nome",
            new_name="curso_graduacao3",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="data_acad_fim",
            new_name="data_acad_fim1",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="data_acad_inicio",
            new_name="data_acad_fim2",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="situacao_academica",
            new_name="grau_escolaridade1",
        ),
        migrations.AddField(
            model_name="usuario",
            name="data_acad_fim3",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="data_acad_inicio1",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="data_acad_inicio2",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="data_acad_inicio3",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="grau_escolaridade2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="grau_escolaridade3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="instituicao_nome1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="instituicao_nome2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="instituicao_nome3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="situacao_academica1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="situacao_academica2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="situacao_academica3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
