# Generated by Django 4.1 on 2025-09-11 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_hub", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=250)),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="fotos_hub/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "jpeg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuariobase",
            name="foto",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="fotos_perfil/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
    ]
