# Generated by Django 4.1 on 2025-12-01 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_eventos_treinamentos_usuariotreinamentos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariotreinamentos",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
