# Generated by Django 4.1 on 2025-11-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_curso_graduacao_usuario_curso_graduacao1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experienciaprofissional",
            options={},
        ),
        migrations.RenameField(
            model_name="cursoextracurricular",
            old_name="carga_horaria",
            new_name="carga_horaria1",
        ),
        migrations.RenameField(
            model_name="cursoextracurricular",
            old_name="data_conclusao",
            new_name="data_conclusao1",
        ),
        migrations.RenameField(
            model_name="cursoextracurricular",
            old_name="instituicao",
            new_name="instituicao1",
        ),
        migrations.RenameField(
            model_name="cursoextracurricular",
            old_name="nome_curso",
            new_name="instituicao2",
        ),
        migrations.RenameField(
            model_name="cursoextracurricular",
            old_name="link_certificado",
            new_name="link_certificado1",
        ),
        migrations.RenameField(
            model_name="experienciaprofissional",
            old_name="cargo",
            new_name="cargo1",
        ),
        migrations.RenameField(
            model_name="experienciaprofissional",
            old_name="nome_empresa",
            new_name="cargo2",
        ),
        migrations.RenameField(
            model_name="experienciaprofissional",
            old_name="tipo_contrato",
            new_name="cargo3",
        ),
        migrations.RenameField(
            model_name="experienciaprofissional",
            old_name="data_fim",
            new_name="data_fim1",
        ),
        migrations.RenameField(
            model_name="experienciaprofissional",
            old_name="data_inicio",
            new_name="data_fim2",
        ),
        migrations.RenameField(
            model_name="idioma",
            old_name="idioma",
            new_name="idioma1",
        ),
        migrations.RenameField(
            model_name="idioma",
            old_name="nivel_fluencia",
            new_name="idioma2",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="competencias_comportamentais",
            new_name="competencias_comportamentais1",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="competencias_tecnicas",
            new_name="competencias_comportamentais2",
        ),
        migrations.RemoveField(
            model_name="experienciaprofissional",
            name="descricao_atividades",
        ),
        migrations.RemoveField(
            model_name="experienciaprofissional",
            name="emprego_atual",
        ),
        migrations.RemoveField(
            model_name="experienciaprofissional",
            name="empresa_cidade",
        ),
        migrations.RemoveField(
            model_name="experienciaprofissional",
            name="empresa_estado",
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="carga_horaria2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="carga_horaria3",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="data_conclusao2",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="data_conclusao3",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="instituicao3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="link_certificado2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="link_certificado3",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="nome_curso1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="nome_curso2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cursoextracurricular",
            name="nome_curso3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="experienciaprofissional",
            name="data_fim3",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experienciaprofissional",
            name="data_inicio1",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experienciaprofissional",
            name="data_inicio2",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experienciaprofissional",
            name="data_inicio3",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experienciaprofissional",
            name="nome_empresa1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="experienciaprofissional",
            name="nome_empresa2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="experienciaprofissional",
            name="nome_empresa3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="idioma",
            name="idioma3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="idioma",
            name="nivel_fluencia1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="idioma",
            name="nivel_fluencia2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="idioma",
            name="nivel_fluencia3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="competencias_comportamentais3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="competencias_tecnicas1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="competencias_tecnicas2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="competencias_tecnicas3",
            field=models.TextField(blank=True, null=True),
        ),
    ]
