# Generated by Django 4.1 on 2025-09-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hub_usuariobase_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
