# Generated by Django 4.1 on 2025-12-01 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_usuariotreinamentos_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarioeventos",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
