# Generated by Django 4.1 on 2025-09-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_cidade_options_alter_estado_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cidade",
            options={},
        ),
        migrations.AlterModelOptions(
            name="estado",
            options={},
        ),
        migrations.AddField(
            model_name="usuariobase",
            name="hubs",
            field=models.ManyToManyField(blank=True, to="core.hub"),
        ),
    ]
