# Generated by Django 4.1 on 2025-09-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_cidade_options_alter_estado_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariobase",
            name="hubs",
        ),
    ]
