# Generated by Django 4.1 on 2025-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_usuarioeventos_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hub",
            old_name="descricao",
            new_name="descricao_hub",
        ),
        migrations.RenameField(
            model_name="hub",
            old_name="foto",
            new_name="foto_hub",
        ),
        migrations.AddField(
            model_name="hub",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
    ]
