# Generated by Django 4.1 on 2025-12-17 20:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_descricao_hub_descricao_hub_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_noticia", models.CharField(max_length=250)),
                ("descricao_noticia", models.CharField(max_length=250)),
                ("fonte", models.CharField(max_length=50)),
                ("url", models.URLField(blank=True, null=True)),
                ("isActive", models.BooleanField(default=True)),
                ("isHome", models.BooleanField(default=True)),
                (
                    "imagem_noticia",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="fotos_noticia/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "jpeg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoticiaHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hub"
                    ),
                ),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.noticia"
                    ),
                ),
            ],
        ),
    ]
