# Generated by Django 4.1 on 2026-01-09 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_noticia_noticiahub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="nome_hub",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="imagem_noticia",
            field=models.ImageField(
                blank=True,
                db_column="foto_hub",
                default=None,
                null=True,
                upload_to="fotos_noticia/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
    ]
