# Generated by Django 4.1 on 2026-04-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_hub_nome_hub_alter_noticia_imagem_noticia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariotreinamentos",
            name="treinamento",
        ),
        migrations.RemoveField(
            model_name="usuariotreinamentos",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Treinamentos",
        ),
        migrations.DeleteModel(
            name="UsuarioTreinamentos",
        ),
    ]
