# Generated by Django 4.1 on 2026-04-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_usuariotreinamentos_treinamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioeventos',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='usuarioeventos',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.DeleteModel(
            name='UsuarioEventos',
        ),
    ]
