# Generated by Django 4.1 on 2026-05-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_usuarioeventos_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
    ]
