# Generated by Django 4.1 on 2026-04-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_alter_evento_hub"),
        ("treinamento", "0004_alter_treinamento_hub"),
        ("empresa", "0002_alter_empresa_hubs_alter_empresahub_hub"),
        ("core", "0009_remove_usuarioeventos_evento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticiahub",
            name="hub",
        ),
        migrations.RemoveField(
            model_name="noticiahub",
            name="noticia",
        ),
        migrations.DeleteModel(
            name="Hub",
        ),
        migrations.DeleteModel(
            name="Noticia",
        ),
        migrations.DeleteModel(
            name="NoticiaHub",
        ),
    ]
