# Generated by Django 4.1 on 2026-08-20 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260603_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('vaga_criada', 'Vaga criada'), ('candidatura_criada', 'Candidatura registrada'), ('candidatura_cancelada', 'Candidatura cancelada'), ('contratacao_sinalizada', 'Contratação sinalizada'), ('evento_criado', 'Evento criado'), ('treinamento_criado', 'Treinamento criado'), ('reserva_espaco', 'Reserva de espaço do Hub'), ('hub_criado', 'Hub criado'), ('hub_alterado', 'Hub alterado'), ('hub_toggle', 'Hub ativado/desativado'), ('noticia_criada', 'Notícia criada'), ('noticia_alterada', 'Notícia alterada'), ('noticia_toggle', 'Notícia ativada/desativada'), ('usuario_desativado', 'Usuário desativado/reativado')], max_length=50)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Ação',
                'verbose_name_plural': 'Logs de Ação',
                'ordering': ['-data_hora'],
            },
        ),
    ]
