# Generated by Django 4.1 on 2025-07-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TblCurriculo",
            fields=[
                ("intIdCurriculo", models.AutoField(primary_key=True, serialize=False)),
                ("txtCargoPretendido", models.CharField(max_length=100)),
                ("txtAreaInteresse", models.CharField(max_length=100)),
                (
                    "decPretensaoSalarial",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("txtDisponibilidade", models.CharField(max_length=100)),
                ("txtCurriculoPdf", models.TextField()),
                ("txtCartaApresentacao", models.TextField()),
                ("bolDisponibilidadeRemoto", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="TblUsuario",
            fields=[
                ("intIdUsuario", models.AutoField(primary_key=True, serialize=False)),
                ("txtNomeCompleto", models.CharField(max_length=255)),
                (
                    "txtNomeSocial",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("datNascimento", models.DateField()),
                (
                    "txtGenero",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Feminino", "Feminino"),
                            ("Outro", "Outro"),
                            ("Prefiro não dizer", "Prefiro não dizer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "txtEstadoCivil",
                    models.CharField(
                        choices=[
                            ("Solteiro", "Solteiro"),
                            ("Casado", "Casado"),
                            ("Divorciado", "Divorciado"),
                            ("Viúvo", "Viúvo"),
                            ("Outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("txtNacionalidade", models.CharField(max_length=100)),
                ("txtTelefonePrincipal", models.CharField(max_length=20)),
                (
                    "txtTelefoneSecundario",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("txtCEP", models.CharField(max_length=10)),
                ("txtRua", models.CharField(max_length=255)),
                ("txtNumero", models.CharField(max_length=10)),
                (
                    "txtComplemento",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("intIdCidade", models.IntegerField()),
                ("intIdEstado", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TblSkill",
            fields=[
                ("intIdSkill", models.AutoField(primary_key=True, serialize=False)),
                ("txtSkill", models.CharField(max_length=100)),
                (
                    "intIdCurriculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.tblcurriculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblRedesSociais",
            fields=[
                (
                    "intIdRedesSociais",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "txtLinkedin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("txtGithub", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "txtSitePessoal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "txtInstagram",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "txtFacebook",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "intIdCurriculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.tblcurriculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblIdioma",
            fields=[
                ("intIdIdioma", models.AutoField(primary_key=True, serialize=False)),
                ("txtIdioma", models.CharField(max_length=100)),
                ("txtNivelFluencia", models.CharField(max_length=100)),
                (
                    "intIdCurriculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.tblcurriculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblFormacaoAcademica",
            fields=[
                ("intIdFormacao", models.AutoField(primary_key=True, serialize=False)),
                ("txtNomeInstituicao", models.CharField(max_length=255)),
                ("txtGrau", models.CharField(max_length=100)),
                ("txtCurso", models.CharField(max_length=255)),
                (
                    "txtSituacao",
                    models.CharField(
                        choices=[
                            ("Cursando", "Cursando"),
                            ("Concluído", "Concluído"),
                            ("Trancado", "Trancado"),
                            ("Abandonado", "Abandonado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("datInicio", models.DateField()),
                ("datConclusao", models.DateField(blank=True, null=True)),
                (
                    "intIdCurriculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.tblcurriculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblExperienciaProfissional",
            fields=[
                (
                    "intIdExperiencia",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("txtNomeEmpresa", models.CharField(max_length=255)),
                ("txtCargo", models.CharField(max_length=100)),
                (
                    "txtTipoContrato",
                    models.CharField(
                        choices=[
                            ("CLT", "CLT"),
                            ("PJ", "PJ"),
                            ("Freelancer", "Freelancer"),
                            ("Estágio", "Estágio"),
                            ("Temporário", "Temporário"),
                            ("Outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("txtLocal", models.CharField(max_length=255)),
                ("txtDescricao", models.TextField()),
                ("datPeriodoInicio", models.DateField()),
                ("datPeriodoFim", models.DateField(blank=True, null=True)),
                (
                    "intIdCurriculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.tblcurriculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TblCurso",
            fields=[
                ("intIdCurso", models.AutoField(primary_key=True, serialize=False)),
                ("txtNomeCurso", models.CharField(max_length=255)),
                ("txtInstituicao", models.CharField(max_length=255)),
                ("intCargaHoraria", models.IntegerField()),
                ("datConclusao", models.DateField()),
                (
                    "intIdCurriculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.tblcurriculo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tblcurriculo",
            name="intIdUsuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="usuario.tblusuario"
            ),
        ),
        migrations.CreateModel(
            name="TblAcessibilidade",
            fields=[
                (
                    "intIdAcessibilidade",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("bolPCD", models.BooleanField()),
                ("txtTipoDeficiencia", models.CharField(max_length=255)),
                ("txtNecessidadeAdaptacao", models.TextField()),
                (
                    "intIdCurriculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.tblcurriculo",
                    ),
                ),
            ],
        ),
    ]
