# Generated by Django 4.1 on 2025-07-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tblusuario",
            name="intIdCidade",
        ),
        migrations.RemoveField(
            model_name="tblusuario",
            name="intIdEstado",
        ),
        migrations.AddField(
            model_name="tblusuario",
            name="txtCidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tblusuario",
            name="txtEstado",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tblacessibilidade",
            name="intIdCurriculo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acessibilidade",
                to="usuario.tblcurriculo",
            ),
        ),
        migrations.AlterField(
            model_name="tblacessibilidade",
            name="txtNecessidadeAdaptacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tblacessibilidade",
            name="txtTipoDeficiencia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tblcurriculo",
            name="intIdUsuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculo",
                to="usuario.tblusuario",
            ),
        ),
        migrations.AlterField(
            model_name="tblcurriculo",
            name="txtCartaApresentacao",
            field=models.FileField(blank=True, null=True, upload_to="cartas/"),
        ),
        migrations.AlterField(
            model_name="tblcurriculo",
            name="txtCurriculoPdf",
            field=models.FileField(upload_to="curriculos/"),
        ),
        migrations.AlterField(
            model_name="tblcurriculo",
            name="txtDisponibilidade",
            field=models.CharField(
                choices=[
                    ("manha", "Manhã"),
                    ("tarde", "Tarde"),
                    ("integral", "Integral"),
                    ("noturno", "Noturno"),
                    ("fim_de_semana", "Fins de semana"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tblcurso",
            name="intIdCurriculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos",
                to="usuario.tblcurriculo",
            ),
        ),
        migrations.AlterField(
            model_name="tblexperienciaprofissional",
            name="intIdCurriculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiencias",
                to="usuario.tblcurriculo",
            ),
        ),
        migrations.AlterField(
            model_name="tblformacaoacademica",
            name="intIdCurriculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formacoes",
                to="usuario.tblcurriculo",
            ),
        ),
        migrations.AlterField(
            model_name="tblidioma",
            name="intIdCurriculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idiomas",
                to="usuario.tblcurriculo",
            ),
        ),
        migrations.AlterField(
            model_name="tblredessociais",
            name="intIdCurriculo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redes",
                to="usuario.tblcurriculo",
            ),
        ),
        migrations.AlterField(
            model_name="tblskill",
            name="intIdCurriculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="usuario.tblcurriculo",
            ),
        ),
    ]
