# Generated by Django 4.1 on 2025-09-26 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nomefantasia", models.CharField(default=False, max_length=100)),
                ("tipo_empresa", models.CharField(default=False, max_length=100)),
                ("razao_social", models.CharField(default=False, max_length=255)),
                ("cnpj", models.CharField(default=False, max_length=20)),
                ("telefone", models.CharField(default=False, max_length=20)),
                ("rua", models.CharField(default=False, max_length=255)),
                ("cep", models.CharField(default=False, max_length=10)),
                ("numero", models.IntegerField(default=False)),
                ("complemento", models.CharField(default=False, max_length=25)),
                ("segmento", models.CharField(default=False, max_length=100)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.cidade"
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.estado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmpresaHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hub"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empresa",
            name="hubs",
            field=models.ManyToManyField(through="empresa.EmpresaHub", to="core.hub"),
        ),
    ]
