# Generated by Django 4.1 on 2025-10-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="hubs",
            field=models.ManyToManyField(
                blank=True, null=True, through="empresa.EmpresaHub", to="core.hub"
            ),
        ),
        migrations.AlterField(
            model_name="empresahub",
            name="hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hub",
            ),
        ),
    ]
