# Generated by Django 4.1 on 2025-09-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_hub_usuariobase_foto"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empresa",
            name="hubs",
            field=models.ManyToManyField(through="empresa.EmpresaHub", to="core.hub"),
        ),
        migrations.AddField(
            model_name="empresahub",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="empresa.empresa"
            ),
        ),
        migrations.AddField(
            model_name="empresahub",
            name="hub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.hub"
            ),
        ),
    ]
