# Generated by Django 4.1 on 2025-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_empresahub_empresa_hubs_empresahub_empresa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="segmentos",
        ),
        migrations.AddField(
            model_name="empresa",
            name="segmento",
            field=models.CharField(default="default", max_length=100),
        ),
        migrations.DeleteModel(
            name="EmpresaSegmento",
        ),
        migrations.DeleteModel(
            name="Segmento",
        ),
    ]
