# Generated by Django 4.1 on 2026-04-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("treinamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricaotreinamento",
            name="presenca",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("presente", "Presente"),
                    ("ausente", "Ausente"),
                ],
                default="pendente",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ListaEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
                (
                    "treinamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lista_espera",
                        to="treinamento.treinamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["data_entrada"],
                "unique_together": {("treinamento", "usuario")},
            },
        ),
    ]
