# Generated by Django 4.1 on 2026-04-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("treinamento", "0002_inscricaotreinamento_presenca_listaespera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscricaotreinamento",
            name="treinamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscricoes",
                to="treinamento.treinamento",
            ),
        ),
    ]
