# Generated by Django 4.1 on 2026-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0003_alter_inscricaotreinamento_treinamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='isActivate',
            field=models.BooleanField(default=True),
        ),
    ]
