# Generated by Django 4.1 on 2026-04-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0001_initial"),
        ("treinamento", "0003_alter_inscricaotreinamento_treinamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treinamento",
            name="hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treinamentos",
                to="hubs.hub",
            ),
        ),
    ]
